apiVersion: v1
kind: Pod
metadata:
  name: my-pod-2
  labels:
    app: nginx
    environment: development
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: sidecar
      image: busy-box
      args: ["sleep", "3600"]
