apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: nginx

          env:
            - name: App
              valueFrom:
                configMapKeyRef:
                  name: frontend-cm
                  key: APP_NAME
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: frontend-cm
                  key: ENVIRONMENT

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000
